CREATE TABLE `orcamentos` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`id_cliente` integer,
	`nome_cliente` text NOT NULL,
	`cpf_cnpj` text,
	`endereco` text,
	`endereco_entrega` text,
	`bairro` text,
	`cidade` text,
	`cep` text,
	`estado` text,
	`telefone` text,
	`email` text,
	`id_produto` integer NOT NULL,
	`produto_nome` text NOT NULL,
	`qtd` real NOT NULL,
	`valor_unit` integer NOT NULL,
	`total` integer NOT NULL,
	`id_vendedor` integer NOT NULL,
	`id_forma_pgto` integer NOT NULL,
	`id_empresa` integer NOT NULL,
	`id_usuario` integer NOT NULL,
	`data_orcamento` integer DEFAULT (strftime('%s', 'now')),
	`validade_orcamento` integer,
	`distancia_obra` real,
	`bomba_necessaria` integer DEFAULT 0,
	`status` text DEFAULT 'PENDENTE',
	`obs` text,
	`created_at` integer DEFAULT (strftime('%s', 'now')),
	`updated_at` integer,
	`deleted_at` integer,
	FOREIGN KEY (`id_cliente`) REFERENCES `clientes`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`id_produto`) REFERENCES `produtos`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`id_vendedor`) REFERENCES `vendedores`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`id_forma_pgto`) REFERENCES `forma_pgto`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`id_empresa`) REFERENCES `empresas`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`id_usuario`) REFERENCES `usuarios`(`id`) ON UPDATE no action ON DELETE no action
);
